---

- name: Configure Jenkins Port
  lineinfile: dest=/etc/default/jenkins regexp=^HTTP_PORT= line=HTTP_PORT={{port}}
  register: config_changed

- name: Restart jenkins now
  service: name=jenkins state=restarted
  when: config_changed.changed
