---

- include: repo.yml

- include: dependencies_deb.yml

- name: Install Jenkins
  apt: name=jenkins state=latest
  register: jenkins_install
  when: ansible_os_family == "Debian"

- include: config.yml

- include: cli.yml

- include: plugins.yml

